name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: casiez/oneeurofilter:latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make

